ridiculousfish/regress

src/parse.rs
Changes:
- Implements `std::error::Error` on `regress::Error` as described in the [Rust API guidelines](https://rust-lang.github.io/api-guidelines) in section Interoperability ([C-GOOD-ERROR](https://rust-lang.github.io/api-guidelines/interoperability.html#c-good-err))
- Implements extra derives (like `PartialEq`, `Eq`, `Hash`, etc) section Interoperability ([C-COMMON-TRAIS](https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits))
These changes are very common and are usually expected in an API, the biggest being implementing `std::error::Error` which allows so we can return an `Box<dyn std::error::Error>` and crates like `anyhow`, `error-chain` to work. The second one is less important but it is nice to have. Initially …
=> Implement `std::error::Error` and extra derives for `regress::Error`

src/api.rs
Changes:
- Implement `std::str::FromStr` for `regress::Regex`
If a type implements `FromStr` it can use the `str::parse()` method, with this we can do:
```rust
let re: Regex = "abc".parse().unwrap();
```
=> Implement `FromStr` for Regex

src/api.rs, src/bin/tester.rs, src/lib.rs, tests/common/mod.rs
Changes:
- Rename `Regex::newf` to `Regex::with_flags`
This is done because `newf` is not a descriptive name for a function that constructs a regex with flags, a better name is `with_flags()` with makes it clear what the function does and follows the Rust APIs guidelines section Naming ([C-CASE](https://rust-lang.github.io/api-guidelines/naming.html)) which states that the constructor name should be `new` or `with_more_detail` this is the same as `Vec::with_capacity()`, there are cases where it makes sense to use different naming like `File::open` as described in [here](https://rust-lang.github.io/api-guidelines/predictability.html?highlight=file::open#constructors-are-static-inherent-methods-c-ctor)
=> Rename `Regex::newf` to `Regex::with_flags`

.github/workflows/rust.yml
Changes:
- CI `cargo check` on linux
- CI `cargo check` on windows
- CI `cargo test` on linux
- CI `cargo test` on windows
- CI `cargo clippy` check
- CI `cargo fmt` check
- CI `cargo doc` check
This PR add a some continuous integration checks as mentioned above, this is a really nice thing to have to catch failing tests, lints or formatting before merging to master.
**NOTE**: for this to work github actions must be enabled, It can be enabled through the `Actions` repo tab.
=> Continuous integration

tests/common/mod.rs, tests/pcre_tests.rs, tests/syntax_error_tests.rs, tests/tests.rs
These attributes were generating some warnings since they are deprecated an `#[rustfmt::skip]` should be used instead.
=> Remove use of deprecated attributes in tests

Cargo.toml, README.md, src/api.rs, src/bin/tester.rs
- Make `tester` the default bin, so we can run `cargo run` instead of `cargo run --bin tester`
- Remove `dump-phase` flag feature.
- Added dump flags for dumping.
- Remove dump flags from `Flags`
- Refactor `tester` to use `structopt` crate
- Fix wrong counting of matches
- Add help message to cli options/flags
=> Improve `tester` bin

rustfmt.toml
Rustfmt was generating some warnings about: `wrap_comments` since it is not stabilized and only available in nightly channel. So I'm commenting it out for now until its stable
warnings generated:
```
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
```
=> Comment out the nightly fmt feature

README.md, src/api.rs
Public functions should be marked with the `#[inline]` attribute so the compiler can inline them, otherwise it wont inline it in cross-crate linking
more info: <https://stackoverflow.com/a/37639889>
=> `#[inline]` on pub functions

src/api.rs, src/lib.rs
With having Flags implement `From<&str>` we can make Regex::with_flags accept anything that implements `Into<Flags>` (automatically implemented by From trait),
```rust 
Regex::with_flags("abc", "i")
```
```rust
let flags = Flags::from("i");
Regex::with_flags("abc", flags)
```
This makes the API a bit nicer.
=> Implement `From<&str>` for Flags and improve `Regex::with_flags`

src/api.rs, src/bin/tester.rs, src/classicalbacktrack.rs, src/lib.rs, src/pikevm.rs, tests/common/mod.rs
- Renames `Match::total()` => `Match::range()` - the function name `total` does not describe what it returns.
- Add `Match::start()`
- Add `Match::end()`
This matches what the `regex` crate does.
=> Rename `Match::total()` to `Match::range()` and `start` and `end` accessors

Cargo.toml, src/api.rs, src/bytesearch.rs, src/classicalbacktrack.rs, src/codepointset.rs, src/cursor.rs, src/emit.rs, src/exec.rs, src/indexing.rs, src/insn.rs, src/ir.rs, src/lib.rs, src/matchers.rs, src/optimizer.rs, src/parse.rs, src/pikevm.rs, src/position.rs, src/startpredicate.rs, src/types.rs, src/unicode.rs, src/util.rs
It's great to support `no_std`
1. Rename `std` to `core` and `alloc`.
2. use `hashbrown` replace `std`
=> feat: Support `no_std`

src/api.rs, src/parse.rs, tests/syntax_error_tests.rs, tests/tests.rs
I ran into a related issue in boa_engine: https://github.com/boa-dev/boa/issues/2325
I have no idea how to read the ECMAScript documentation, but the introduced behavior is the behavior of regex engines in V8 and SpiderMonkey.
while this commit doesn't seem to fix it in Boa, I believe this change is needed anyway.
=> parse "unbalanced" right square bracket as a literal character

src/parse.rs, tests/tests.rs
closes #53 
I don't see a way to make it good without refactoring the whole parser
=> [non-unicode] less strict QuantifierPrefix parsing

src/parse.rs, tests/common/mod.rs, tests/syntax_error_tests.rs, tests/tests.rs
~~This adds the `"annex-b"` which enables [EcmaScript's Annex-B RegExp syntax](https://tc39.es/ecma262/#sec-regular-expressions-patterns).~~
Regexes like `[a-\s]` and `[--\d]` are allowed in Annex-b and are not treated like a range, but with mach any char rule. This only applies in non-unicode mode.
=> Implement valid character sets in Annex-B

src/parse.rs, tests/tests.rs
stop ignoring errors from trying to parse invalid quantifiers
=> [unicode] fail parsing invalid quantifiers

src/charclasses.rs
This PR adds `U+00A0` to whitespaces which was failing a [test262](https://github.com/tc39/test262/blob/72c0c5e16350a76bd41f7a1ceb7702588a2a39c6/test/built-ins/RegExp/character-class-escape-non-whitespace.js#L25) test
Also updated the spec and added link with comments
=> Add `U+00A0` to whitespaces

src/parse.rs, tests/tests.rs
This PR adds an error when the parser encounters duplicated named capture groups.
It also adds relevant tests from the 262 suite that currently fail.
=> Add parse error for duplicate named groups

src/parse.rs, tests/tests.rs
This PR disallows invalid quantifiers after lookbehinds.
It also adds relevant tests from the 262 suite.
=> Disallow invalid quantifier after lookbehinds

src/emit.rs, src/matchers.rs, src/optimizer.rs, src/parse.rs, src/startpredicate.rs, src/types.rs, tests/tests.rs
This PR implements Unicode Character Classes in Brackets.
=> Implement Unicode Character Classes in Brackets

src/bytesearch.rs, src/startpredicate.rs, src/unicode.rs, src/util.rs
When computing a predicate to match the first byte, we incorrectly assumed that the set of first bytes of a closed interval (in UTF8) are contiguous. But of course this is false. Reimplement this algorithm and add tests.
Fixes #73
=> Correct first-byte computation for interval

gen-unicode/src/binary_properties.rs, gen-unicode/src/general_category_values.rs, gen-unicode/src/scripts.rs, src/parse.rs, tests/tests.rs, tests/unicode_property_escapes.rs
This PR works on the escape parsing.
The PR changes the following:
* Fix a missing flag check where unicode property escapes would be parsed in non-unicode mode.
* Add the unicode flag to some tests because of the above fix.
* Remove the unused `Parser.max_backref` field.
* Move the `Term :: Assertion :: \b` and `Term :: Assertion :: \B` parsing from atom escape parsing to term parsing.
* Add parsing for the case `Term :: ExtendedAtom :: \ [lookahead = c]`.
* Add parsing for the case `ClassEscape :: [~UnicodeMode] c ClassControlLetter`.
* Add parsing for `CharacterEscape :: [~UnicodeMode] LegacyOctalEscapeSequence`.
* Fix errors thrown when `CharacterEscape :: 0 [lookahead ∉ DecimalDigit]`, `CharacterEscape :: HexEscapeSequence :: x HexDigit HexDigit` or `CharacterEscape :: …
=> Fix multiple escape parsing issues

src/parse.rs, tests/syntax_error_tests.rs, tests/tests.rs
This fixes and cleans up some of the logic for parsing and detecting invalid characters in `Atom`s. I also added a relevant 262 test that is fixed by this.
=> Correctly reject characters in Atom PatternCharacter

src/parse.rs, tests/tests.rs
In the case where unicode mode is not set and there are no `GroupName`s in the regex, `\k GroupName` is not parsed as a capture group reference but as the literal character `k` and the literal following group name.
I fixed the 262 tests that check this behaviour.
=> Conditionally parse named capture groups

src/parse.rs, tests/tests.rs
This fixes an invalid quantifier loop. The caused was an invalid loop start offset when two `Node`s where pushed before the quantifier.
=> Fix invalid quantifier loop

Cargo.toml, gen-unicode/Cargo.toml, gen-unicode/README.md, gen-unicode/src/binary_properties.rs, gen-unicode/src/case_folding.rs, gen-unicode/src/general_category_values.rs, gen-unicode/src/main.rs, gen-unicode/src/scripts.rs
This removes our custom parsing for ucd files and migrates it to the `ucd-parse` crate.
=> Refactor unicode generation to fully use ucd-parse

src/parse.rs, tests/tests.rs
In non unicode mode `ClassAtomNoDash :: \ [lookahead = c]` was not being parsed correctly.
=> Fix parsing for invalid control characters in class atoms

src/parse.rs, tests/tests.rs
This PR allows quantifiable assertions in non unicode mode as specified in the annexB regex syntax.
=> Allow quantifiable assertions in non unicode mode

gen-unicode/src/binary_properties.rs, gen-unicode/src/general_category_values.rs, gen-unicode/src/main.rs, gen-unicode/src/scripts.rs, src/indexing.rs, src/parse.rs, src/scm.rs, src/unicode.rs, src/unicodetables.rs
Depends on #81. This PR only contains 3de0640ac37d71c535e43de8bd69743d9efc0373.
This PR changes:
- Change unicode `is_*` functions to take `u32` instead of `char` to allow matching for all invalid `char` codepoints.
- Add a special case of the unicode property `Any`, because it's negative should not match an empty string.
- Add a missing underflow check in utf16 decoding.
- Add a special case for the script extension codepoints of `Common` and `Inherited`. Any codepoints that are contained in other script's extensions, must be removed from those two.
=> Fix remaining unicode script tests

Cargo.toml
@ridiculousfish With the latest PRs merged, regress now passes all test262 tests with the following exceptions:
- Tests with the `regexp-v-flag` proposal flag. This proposal is merged into the spec and I'm looking to implement it next.
- Tests with the `regexp-duplicate-named-groups` proposal flag. This proposal is in stage 3.
- Tests with the `legacy-regexp` proposal flag. This proposal is in stage 3.
- One test that depends on unicode 15.1 tables. Currently the test262 tests are divided between unicode 15.0 and 15.1.
I think this is a good point to publish a release :)
=> Prepare the v0.8.0 release

src/lib.rs
I've been looking for a regex impl for my toy JavaScript implementation ([mcjs](https://github.com/sebastiano-barrera/mcjs/)), and I thought `regress` sounded good but still insufficient due to the lack of support for searching on UTF-16 strings.
Turns out, `regress` _does_ do exactly what I need! It's just nowhere to be found in the [crate documentation](https://docs.rs/regress) (at least not without following the 'Feature flags' link, which I had no reason to, I think). I only found this out by looking at what [boa does](https://github.com/boa-dev/boa/blob/109dd3d395859fcf0d8ecdc01b146b517437716e/core/engine/src/builtins/regexp/mod.rs#L976) for its own RegExp implementation.
So, I hope this little extra paragraph will be useful for the next one who walks my path.
Let me know if you'd …
=> add documentation for feature `utf16`

.github/workflows/rust.yml, Cargo.toml, src/api.rs, src/classicalbacktrack.rs, src/emit.rs, src/insn.rs, src/parse.rs, src/pikevm.rs, tests/tests.rs
Prior to this commit, the Match::named_groups() function would return names in an arbitrary order, because they were stored in a hash table. Switch to returning them in the original specification order from the pattern. This allows implementing the JS engine semantics where the object key order matches that from the pattern.
Fixes #96
=> Named captures to return their names in-order
